name: Center Stage Cafe
favicon: null
layout_spectrum: 0.6613870717119426
typography_spectrum: 0.5464846657123417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9818620611913502
  lightness: 0.6308002597652376
  saturation: 0.8518335348926485
  rhythmicContrast: 0.5174486229661852
purpose: []
